apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: crossview
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: crossview
    app.kubernetes.io/version: v3.9.0-rc.4
    app.tanka.grafana.com: crossplane
    helm.sh/chart: crossview-3.9.0-rc.4
  name: crossview-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - configmaps
  - secrets
  - events
  - nodes
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.crossplane.io
  resources:
  - managedresourceactivationpolicies
  - managedresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
