{
  homebrew = {
    # Whether to enable nix-darwin to manage installing/updating/upgrading Homebrew taps, formulae,
    # and casks, as well as Mac App Store apps and Docker containers, using Homebrew Bundle.
    # NOTE : that enabling this option does not install Homebrew, see the Homebrew website for
    #        installation instructions.
    enable = true;

    # Whether to enable Homebrew to automatically use the Brewfile that this module generates in
    # the Nix store, when you manually invoke brew bundle.
    global.brewfile = true;

    masApps = { };

    caskArgs.no_quarantine = true;
    casks = [
      "betterdisplay"
      "raycast"
      "vlc"
      "discord"
      "protonvpn"
      "aviatrix-vpn-client"
    ];

    taps = [ ];

    brews = [
      "pinentry-mac"
      "yubikey-personalization"
      "terminal-notifier"
      "riscv64-elf-gdb"
    ];

    onActivation = {
      # Whether to enable Homebrew to auto-update itself and all formulae during nix-darwin system
      # activation.
      autoUpdate = true;

      # Whether to enable Homebrew to upgrade outdated formulae and Mac App Store apps during
      # nix-darwin system activation.
      upgrade = true;

      # This option manages what happens to formulae installed by Homebrew, that aren’t present in
      # the Brewfile generated by this module, during nix-darwin system activation.
      #
      # When set to "zap", nix-darwin invokes brew bundle [install] with the --cleanup --zap flags.
      # This uninstalls all formulae not listed in the generated Brewfile, and if the formula is a
      # cask, removes all files associated with that cask.
      cleanup = "zap";
    };
  };
}
