set -g @plugin "tmux-plugins/tpm"

# Tmux theme.
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_window_id_style none
set -g @tokyo-night-tmux_pane_id_style none
set -g @tokyo-night-tmux_zoom_id_style sub

# Adds sensible bindings for tmux.
set -g @plugin "tmux-plugins/tmux-sensible"

# Autoreloads tmux configuration.
set -g @plugin "b0o/tmux-autoreload"

run "~/.tmux/plugins/tpm/tpm"
