apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugger
spec:
  selector:
    matchLabels:
      app: debugger
  replicas: 1
  template:
    metadata:
      labels:
        app: debugger
    spec:
      containers:
        - name: debugger
          image: registry.k8s.io/e2e-test-images/agnhost:2.40
          command: ["sh", "-c", "sleep infinity"]
          stdin: true
          tty: true
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
