apiVersion: v1
kind: Pod
metadata:
  name: debugger
spec:
  containers:
    - name: debugger
      image: ubuntu:latest
      command: ["sh", "-c", "sleep infinity"]
      stdin: true
      tty: true
