# https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

exec = gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-dracula'
exec = gsettings set org.gnome.desktop.interface gtk-theme 'Catppuccin-Mocha'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
	gaps_in = 3
	gaps_out = 8

	border_size = 2

	# https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
	col.active_border = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
	col.inactive_border = rgba(b4befecc) rgba(6c7086cc) 45deg

	layout = dwindle

	# Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
	allow_tearing = false

	# Set to true enable resizing windows by clicking and dragging on borders and gaps
	resize_on_border = true
}

group {
	col.border_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
	col.border_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
	col.border_locked_active = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
	col.border_locked_inactive = rgba(b4befecc) rgba(6c7086cc) 45deg
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
	rounding = 10
	dim_special = 0.3

	# https://wiki.hyprland.org/Configuring/Variables/#blur
	blur {
		enabled = yes
		size = 6
		passes = 3
		new_optimizations = on
		ignore_opacity = on
		xray = false
		special = true
	}
}

layerrule = blur,waybar

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
	enabled = true

	# Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

	bezier = myBezier, 0.05, 0.9, 0.1, 1.05

	animation = windows, 1, 7, myBezier
	animation = windowsOut, 1, 7, default, popin 80%
	animation = border, 1, 10, default
	animation = borderangle, 1, 8, default
	animation = fade, 1, 7, default
	animation = workspaces, 1, 6, default
}

# Dwindle is a BSPWM-like layout, where every window on a workspace is a member of a binary tree.
# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more.
dwindle {
	# Pseudotiled windows retain their floating size when tiled.
	pseudotile = true

	# By default, Dwindle splits are not permanent. The split is determined dynamically with the W/H
	# ratio of the parent node.
	preserve_split = true
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
	new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
	force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
	disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}
